### ISSUE TITLE
Update Readme for ANS

### ISSUE THREAD

**Issue by gonuke** [katyhuff/2015-11-11-ans#1]
Great talk @katyhuff - looking forward to using this and the notebooks!!

**Comment by gonuke** [comment]
I would have put a winking emoticon in the issue, but was unsure of the etiquette :)

**Comment by katyhuff** [comment]
Excellent @gonuke! Notebooks being produced at
github.com/physics-codes/seminar . Some notebooks not complete/tested. Will
tag a first release set very soon!

On Wed, Nov 11, 2015 at 2:02 PM, Paul Wilson notifications@github.com
wrote:

> I would have put a winking emoticon in the issue, but was unsure of the
> etiquette :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/katyhuff/2015-11-11-ans/issues/1#issuecomment-155878786
> .

## 

http://katyhuff.github.com
